name: tautulli-mtonnie 
version: '0.1' 
summary: A python based web application for monitoring, analytics and notifications for Plex Media Server 
description: |
  to be completed

grade:devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  tautulli:
    plugin: python
    python-version: python2
    source: https://github.com/Tautulli/Tautulli.git
 
