name: tautulli-mtonnie 
version: '0.1' 
summary: A Python based monitoring and tracking tool for Plex Media Server
description: |
  Tautulli is a 3rd party application that you can run alongside your Plex Media Server to monitor activity and track various statistics.
  Most importantly, these statistics include what has been watched, who watched it, when and where they watched it, and how it was watched.
  The only thing missing is "why they watched it", but who am I to question your 42 plays of Frozen. 
  All statistics are presented in a nice and clean interface with many tables and graphs, which makes it easy to brag about your server to everyone else.

architectures:
  - build-on: amd64
    run-on: amd64

grade: devel
confinement: devmode # use 'strict' once you have the right plugs and slots

parts:
  tautulli:
    plugin: python
    python-version: python2
    source: https://github.com/Tautulli/Tautulli.git
 
